name: pet-backend
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.3.0
  - _python_abi3_support=1.0
  - aom=3.9.1
  - blas=1.0
  - blinker=1.9.0
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cpuonly=2.0
  - cpython=3.10.18
  - cryptography=45.0.5
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - eigen=3.4.0
  - expat=2.7.1
  - faiss=1.9.0
  - filelock=3.17.0
  - flask-jwt-extended=4.7.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hf-xet=1.1.5
  - huggingface_hub=0.34.4
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libglib=2.84.2
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.5.2
  - packaging=24.2
  - pandas=2.3.1
  - patsy=1.0.1
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.46.4
  - psutil=7.0.0
  - py-cpuinfo=9.0.0
  - pycparser=2.21
  - pyjwt=2.10.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-gil=3.10.18
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - rav1e=0.7.1
  - requests=2.32.4
  - safetensors=0.5.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.50.2
  - statsmodels=0.14.5
  - svt-av1=3.0.2
  - tbb=2021.8.0
  - timm=1.0.19
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - backports-datetime-fromisoformat==2.0.3
      - boto3==1.40.1
      - botocore==1.40.1
      - cachecontrol==0.14.3
      - cachetools==5.5.2
      - click==8.2.1
      - dotenv==0.9.9
      - filetype==1.2.0
      - fire==0.7.0
      - firebase-admin==7.0.0
      - flask==3.1.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-cloud-core==2.4.3
      - google-cloud-firestore==2.21.0
      - google-cloud-storage==3.2.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - grpcio-status==1.73.1
      - h2==4.2.0
      - hpack==4.1.0
      - hyperframe==6.1.0
      - jmespath==1.0.1
      - markdown==3.8.2
      - marshmallow==4.0.0
      - msgpack==1.1.1
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.10.0.84
      - pi-heif==1.0.0
      - pillow-avif-plugin==1.5.2
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybboxes==0.1.6
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dotenv==1.1.1
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - roboflow==1.2.3
      - rsa==4.9.1
      - s3transfer==0.13.1
      - sahi==0.11.31
      - scipy==1.15.3
      - shapely==2.1.1
      - smmap==5.0.2
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - typing-inspection==0.4.1
      - ultralytics==8.3.172
      - ultralytics-thop==2.0.14
      - yolov5==7.0.14
      - openai==1.8.0